- hosts: web
  tasks:
  - name: "Install Httpd server"
    package:
      name: httpd
      state: present
    when: ansible_distribution == "RedHat"
    register: x
  
  - name: create directory
    file:
      state: directory
      dest: "/var/www/web"
    register: y
    tags: web-git

  - name: configure web server
    template:
      dest: /etc/httpd/conf.d/web.conf
      src:  template/web.conf.j2
    when: x.rc == 0
    tags: web-configure
  
  - name: copy web page from url
    get_url:
      dest: "/var/www/web"
      url: "https://github.com/imneeteeshyadav98/Ansible_httpdConfigure/blob/master/webPage/index.html"
    when: y.failed == false
    tags: web-git
  handlers:
  - name: service httpd restrat
    service:
      name: httpd
      state:  restrated
  